// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Wed, 28 Oct 2015 07:51:07 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.1.18928.0")]
[assembly: AssemblyFileVersion("1.1.18928.751")]
